spring:
  profiles:
    active: dev
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    hiddenmethod:
      filter:
        enabled: true
